owner: 7r00t
repo: upptime
user-agent: 7r00t Upptime
sites:
  - name: 7r00t Blog
    url: https://7r00t.github.io
  - name: 7r00t About
    url: https://7r00t.github.io/about
  - name: 7r00t Posts
    url: https://7r00t.github.io/posts
status-website:
  name: 7r00t Status
  logoUrl: https://7r00t.github.io/favicon.png
  theme: dark
assignees:
  - 7r00t
